In [1]:
from datascience import *
import numpy as np
import seaborn as sns

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Data 6: Iteration

# For-loops

## Iterating over a previously assigned array

In [2]:
course_staff = make_array('Yan', 'Villagomez', 'Maneenop', 'Qiao')

for member in course_staff:
    print(member)

Yan
Villagomez
Maneenop
Qiao


## Doing something n-times

In [18]:
for anything in np.arange(3):
    print(str(anything) + "I love Data 6")
    print("!")

0I love Data 6
!
1I love Data 6
!
2I love Data 6
!


In [10]:
for i in np.arange(5):
    print("I love Data 6!!!", i)

I love Data 6!!! 0
I love Data 6!!! 1
I love Data 6!!! 2
I love Data 6!!! 3
I love Data 6!!! 4


In [2]:
for some_number in np.arange(5):
    print("I love Data 6!!!", i)

NameError: name 'i' is not defined

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

## Making a new array

In [ ]:
for i in np.arange(5):
    print("I am counting to 100. I am at", i + 1)

In [3]:
base = 100
numbers = make_array()
for i in np.arange(5):
    numbers = np.append(numbers, base + i)

print(numbers)

[ 100.  101.  102.  103.  104.]


### Fenceposting

* Place one “post” outside your loop
* Alternate between “fences” and “posts” inside your loop

In [7]:
base = 100
numbers = make_array()
for i in np.arange(5):
    print(numbers)
    numbers = np.append(numbers, base + i)

[]
[ 100.]
[ 100.  101.]
[ 100.  101.  102.]
[ 100.  101.  102.  103.]


## Keep track of counters and totals outside of the loop

In [12]:
# what does this code do?
def average(arr):
    total = 0
    count = 0
    for element in arr:
        total += element       # shorthand for    total = total + element
        count += 1             # shorthand for    count = count + 1
    print("total", total)
    print("count", count)
    return total/count

In [13]:
test1 = make_array(1, 2, 3, 4)
average(test1)

total 10
count 4


2.5

In [11]:
np.average(test1)

2.5

In [10]:
average(np.arange(10))

4.5

## Iterating over strings???

In [ ]:
def unknown(word):
    output = ''
    for letter in word:
        if letter not in 'aeiou':
            output += letter
    return output

In [ ]:
unknown("supercalifragilisticexpialidocious")

## Practice: For-loops

In [ ]:
titanic = Table().from_df(sns.load_dataset("titanic"))
titanic

### **Task**: Find the average fare of the first-class passengers.

Using a for-loop and conditional statements:

In [ ]:
ticket_class = titanic.column("class")
ticket_fare = titanic.column("fare")

...
for i in np.arange(len(ticket_class)):
    ...

...

<details>
  <summary>Click for Solution</summary>

Various options. One reasonable approach:

```
ticket_class = titanic.column("class")
ticket_fare = titanic.column("fare")

total = 0
count = 0
for i in np.arange(len(ticket_class)):
    if ticket_class.item(i) == "First":
        total += ticket_fare.item(i) 
        count += 1
total/count
```

</details>



In [ ]:
# double-check with Table methods
titanic.where("class", "First").column("fare").mean()

# While-loops

## Repeat while the condition is *true*

In [ ]:
counter = 10
while counter > 0:
    print(counter)
    counter -= 1
print("blast off!")

### Discussion: What is the difference between these two loops?

Every for-loop can be written as a while-loop, but not vice versa!

In [ ]:
def sum_squares_for(values):
    total = 0
    for v in values:
        total += v ** 2
    return total

sum_squares_for(make_array(3, 4, 5))

In [ ]:
def sum_squares_while(values):
    total = 0
    i = 0
    while i < len(values):
        total += values.item(i) ** 2
        i += 1
    return total

sum_squares_while(make_array(3, 4, 5))

## Practice: More loops

Find the historic year where UC Berkeley enrolled a cumulative number of 1,000,000 undergraduates.

Source: https://www.universityofcalifornia.edu/about-us/information-center/historical-enrollment

In [ ]:
enrollment = Table.read_table("data/ucberkeley_enrollment.csv")
enrollment

In [ ]:
total_undergrads = 0
year_index = 0
undergrads = enrollment.column("undergrad")

while total_undergrads <= 1000000:
    total_undergrads += undergrads.item(year_index)
    year_index += 1

print('Total undergrads graduated by', enrollment.column("year").item(year_index),
      "was", total_undergrads)